### ISSUE TITLE
Remove `heapdump` package

### ISSUE THREAD

**Issue by jthemphill** [naugtur/node-example-heapdump#4]
The `heapdump` package no longer works on modern versions of Node, and [the modern Node docs](https://nodejs.org/en/learn/diagnostics/memory/using-heap-snapshot) still point to this repo as a way to learn how to use V8's heap snapshot inspector in Chrome. Let's remove `heapdump` so this project installs cleanly!

**Comment by naugtur** [comment]
thanks for the nudge!
